INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT ((SELECT COUNT(*) FROM song_masters WHERE id IN ('sm-upload-6c0a0dc9-c4a','sm-upload-66bdb06b-1cb','sm-upload-637470c0-5af','sm-upload-8b4e6e46-206','sm-upload-33959ca1-297','sm-upload-34c51de9-aa4','sm-upload-debc2a1c-66a','sm-upload-b33cfb39-448','sm-upload-89d8af71-0b6','sm-upload-95621150-291','sm-upload-64363012-149','sm-upload-6b506d3e-f76','sm-upload-a4de5316-99a','sm-upload-cc1e80b9-244','sm-upload-0112a6d9-283','sm-upload-2c6e632f-4ae','sm-upload-bba1a72e-f0c','sm-upload-d642ecae-43c','sm-upload-fa2c02f7-a2d','sm-upload-8ca7055e-888','sm-upload-6a381b8f-020','sm-upload-d11b6d58-141') AND album_id IN ('al-version-freesia-wav','al-version-pages-wav'))=22);
WITH c(master_id,source_master_id,cohort,instance_id,entry_id,object_id,title_snapshot,track_snapshot,disc_snapshot,source_track_snapshot,path_snapshot,display_name_snapshot) AS (VALUES
('sm-upload-6c0a0dc9-c4a','1102','freesia','si-upload-6b408867-92e','se-38e2ee65441d4923be354bebf89a9bf1','obj_78c96f0a3be4e75e','Tr.01 人偶之梦',1,NULL,1,'Freesia/wav/Tr.01 人偶之梦.wav','Tr.01 人偶之梦.wav'),
('sm-upload-66bdb06b-1cb','1101','freesia','si-upload-96a13009-f1a','se-5276fcd6541c41c4b618372f7501361c','obj_2fde7e739c042926','Tr.02 泪之诗',NULL,NULL,2,'Freesia/wav/Tr.02 泪之诗.wav','Tr.02 泪之诗.wav'),
('sm-upload-637470c0-5af','1097','freesia','si-upload-90fecd1e-48d','se-ff8599fec6494065a87344757f8f8ba5','obj_a966a361f2a48670','Tr.03 轮回∞Samsara',NULL,NULL,3,'Freesia/wav/Tr.03 轮回∞Samsara.wav','Tr.03 轮回∞Samsara.wav'),
('sm-upload-8b4e6e46-206','1098','freesia','si-upload-bac4cb50-4e0','se-6a79708445cb44c1b6c3819af1995230','obj_ffc38ddae66d7cb1','Tr.04 涟漪',NULL,NULL,4,'Freesia/wav/Tr.04 涟漪.wav','Tr.04 涟漪.wav'),
('sm-upload-33959ca1-297','1107','freesia','si-upload-18b5bdc1-0b3','se-7bb4e873759247be9feccc60df8b7684','obj_801649780593a9b1','Tr.05 雪之花',NULL,NULL,5,'Freesia/wav/Tr.05 雪之花.wav','Tr.05 雪之花.wav'),
('sm-upload-34c51de9-aa4','1100','freesia','si-upload-df11bb86-195','se-22937c758c9348a2aec25fdbddfca336','obj_3092d9dec90192d3','Tr.06 云之翼',NULL,NULL,6,'Freesia/wav/Tr.06 云之翼.wav','Tr.06 云之翼.wav'),
('sm-upload-debc2a1c-66a','1096','freesia','si-upload-963d5910-3e2','se-3ba26e3316ce4602aae24938cb069775','obj_b9943b42a23d56ae','Tr.07 D!s!llus!on',7,NULL,7,'Freesia/wav/Tr.07 D!s!llus!on.wav','Tr.07 D!s!llus!on.wav'),
('sm-upload-b33cfb39-448','1105','freesia','si-upload-fb71d1e6-c47','se-49feac1702a149a8b1d2c171faef261f','obj_3f0dd4874e31b706','Tr.08 D!scolor',NULL,NULL,8,'Freesia/wav/Tr.08 D!scolor.wav','Tr.08 D!scolor.wav'),
('sm-upload-89d8af71-0b6','1099','freesia','si-upload-ae11e589-c9e','se-458b345a66284b90bf7e29b616db8ae7','obj_68d2e803cd35b435','Tr.09 渊之心',NULL,NULL,9,'Freesia/wav/Tr.09 渊之心.wav','Tr.09 渊之心.wav'),
('sm-upload-95621150-291','1106','freesia','si-upload-420af664-f2f','se-cdbaec2c2cad4da687dfce06a239e0e7','obj_bb630ca72a5898bc','Tr.10 心的葬礼',NULL,NULL,10,'Freesia/wav/Tr.10 心的葬礼.wav','Tr.10 心的葬礼.wav'),
('sm-upload-64363012-149','1095','freesia','si-upload-363e88b8-ed8','se-83a2c1f281384f3f9f72874262f61fbf','obj_87ed2ff23cc31c9c','Tr.11 神明废墟',NULL,NULL,11,'Freesia/wav/Tr.11 神明废墟.wav','Tr.11 神明废墟.wav'),
('sm-upload-6b506d3e-f76','1103','freesia','si-upload-8fddb94c-b4d','se-9b5d14369a2540c6b174725bdc10ccec','obj_4d6316c99694296a','Tr.12 Freesia',12,NULL,12,'Freesia/wav/Tr.12 Freesia.wav','Tr.12 Freesia.wav'),
('sm-upload-a4de5316-99a','2029','pages','si-upload-4832434f-29e','se-bb07c72beca44e53824e6db5cd2f7ffb','obj_a017b97683140b01','01 问',NULL,NULL,1,'页间曲-星韵社/wav/01 问.wav','01 问.wav'),
('sm-upload-cc1e80b9-244','2025','pages','si-upload-7644c464-8e0','se-5fcbc8da9b3c4f4ab19d458b57ece85a','obj_eac64617b22155c6','02 星间吟游歌姬',NULL,NULL,2,'页间曲-星韵社/wav/02 星间吟游歌姬.wav','02 星间吟游歌姬.wav'),
('sm-upload-0112a6d9-283','2031','pages','si-upload-f49293a5-7cc','se-2fdb4f3b60ab40a4a752cc284d971ff5','obj_3951ea51a3598435','03 光降落的序章',NULL,NULL,3,'页间曲-星韵社/wav/03 光降落的序章.wav','03 光降落的序章.wav'),
('sm-upload-2c6e632f-4ae','2024','pages','si-upload-0122dfae-08d','se-27f65a4c94b544beba21fcb0cfb80706','obj_4aa1b1019085490e','04 守望与羁绊的微光航行',NULL,NULL,4,'页间曲-星韵社/wav/04 守望与羁绊的微光航行.wav','04 守望与羁绊的微光航行.wav'),
('sm-upload-bba1a72e-f0c','2028','pages','si-upload-c5d11993-46d','se-df471417b9084143a7d96af749a6a9ec','obj_4f01ea7acc0f704d','05 恋に落ちた',NULL,NULL,5,'页间曲-星韵社/wav/05 恋に落ちた.wav','05 恋に落ちた.wav'),
('sm-upload-d642ecae-43c','2027','pages','si-upload-78f0a876-15b','se-a3993c6c76dc4ad9a77e92af6a018db6','obj_7020ea3c9a06d09e','06 恋b',NULL,NULL,6,'页间曲-星韵社/wav/06 恋b.wav','06 恋b.wav'),
('sm-upload-fa2c02f7-a2d','2032','pages','si-upload-7cea7775-c65','se-4453b595d73a475a920ba259f8512cca','obj_3cd07d2e8ca77a3b','07 蝶说，春也可哀，秋也可爱',NULL,NULL,7,'页间曲-星韵社/wav/07 蝶说，春也可哀，秋也可爱.wav','07 蝶说，春也可哀，秋也可爱.wav'),
('sm-upload-8ca7055e-888','2030','pages','si-upload-6cad1008-6e2','se-7fd9ce97284449adbb96e636596f7a0c','obj_99ab13036d3cc476','08 淬火',NULL,NULL,8,'页间曲-星韵社/wav/08 淬火.wav','08 淬火.wav'),
('sm-upload-6a381b8f-020','2033','pages','si-upload-fe564d85-f7c','se-6254b5fb773f40aaa8ae59168410173c','obj_434e631727e6d45c','09 The coming wave',NULL,NULL,9,'页间曲-星韵社/wav/09 The coming wave.wav','09 The coming wave.wav'),
('sm-upload-d11b6d58-141','2026','pages','si-upload-6b09e615-d44','se-8af5096f7f0a4bc4a420de03cf2cebc7','obj_fc7bd9a9e4da4905','10 迟来',NULL,NULL,10,'页间曲-星韵社/wav/10 迟来.wav','10 迟来.wav'))
DELETE FROM song_artists WHERE EXISTS (SELECT 1 FROM c JOIN song_artists source_credit ON source_credit.song_id=c.source_master_id WHERE song_artists.song_id=c.master_id AND song_artists.artist_id=source_credit.artist_id AND song_artists.position=source_credit.position);
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=22);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=1,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-6c0a0dc9-c4a' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-66bdb06b-1cb' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-637470c0-5af' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-8b4e6e46-206' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-33959ca1-297' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-34c51de9-aa4' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=7,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-debc2a1c-66a' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-b33cfb39-448' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-89d8af71-0b6' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-95621150-291' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-64363012-149' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=12,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-6b506d3e-f76' AND album_id='al-version-freesia-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-a4de5316-99a' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-cc1e80b9-244' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-0112a6d9-283' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-2c6e632f-4ae' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-bba1a72e-f0c' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-d642ecae-43c' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-fa2c02f7-a2d' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-8ca7055e-888' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-6a381b8f-020' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='pending-uploads',artist_id='unknown-artist',album_artist_id=NULL,cover_r2_key=NULL,genre=NULL,participants=NULL,lyrics=NULL,lyrics_rich=NULL,track=NULL,disc=NULL,updated_at=unixepoch() WHERE id='sm-upload-d11b6d58-141' AND album_id='al-version-pages-wav';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-e9abb8fbe6','页间曲','页间曲',2025,NULL,NULL,1,0,29797990,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-e9abb8fbe6');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-00d48fe122','页间曲','页间曲',2025,NULL,NULL,1,0,10292617,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-00d48fe122');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-1c10f4d14a','页间曲','页间曲',2025,NULL,NULL,1,0,33962822,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-1c10f4d14a');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-f88b0a5876','页间曲','页间曲',2025,NULL,NULL,1,0,25172852,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-f88b0a5876');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-f249e24866','页间曲','页间曲',2025,NULL,NULL,1,0,33112694,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-f249e24866');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-eb1cffa10c','页间曲','页间曲',2025,NULL,NULL,1,0,28295489,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-eb1cffa10c');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-4abb0b6368','页间曲','页间曲',2025,NULL,NULL,2,0,67144451,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-4abb0b6368');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
INSERT INTO albums (id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) SELECT 'al-8829e799ff','页间曲','页间曲',2025,NULL,NULL,1,0,32699335,0,unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-8829e799ff');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-e9abb8fbe6',updated_at=unixepoch() WHERE id='2025' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-00d48fe122',updated_at=unixepoch() WHERE id='2031' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-1c10f4d14a',updated_at=unixepoch() WHERE id='2024' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-f88b0a5876',updated_at=unixepoch() WHERE id='2028' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-f249e24866',updated_at=unixepoch() WHERE id='2027' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-eb1cffa10c',updated_at=unixepoch() WHERE id='2032' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-4abb0b6368',updated_at=unixepoch() WHERE id='2030' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-8829e799ff',updated_at=unixepoch() WHERE id='2033' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
UPDATE song_masters SET album_id='al-4abb0b6368',updated_at=unixepoch() WHERE id='2026' AND album_id='al-7e5eae45c8';
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=1);
DELETE FROM album_display_group_members WHERE (group_id='ag-version-freesia' AND album_id IN ('al-9544935a62','al-version-freesia-wav')) OR (group_id='ag-version-page-interlude' AND album_id IN ('al-7e5eae45c8','al-version-pages-wav'));
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=4);
DELETE FROM album_display_groups WHERE id IN ('ag-version-freesia','ag-version-page-interlude') AND NOT EXISTS (SELECT 1 FROM album_display_group_members m WHERE m.group_id=album_display_groups.id);
DELETE FROM albums WHERE id IN ('al-version-freesia-wav','al-version-pages-wav') AND NOT EXISTS (SELECT 1 FROM song_masters sm WHERE sm.album_id=albums.id) AND NOT EXISTS (SELECT 1 FROM annotations n WHERE n.item_type='album' AND n.item_id=albums.id) AND NOT EXISTS (SELECT 1 FROM album_display_group_members m WHERE m.album_id=albums.id);
UPDATE albums SET song_count=(SELECT COUNT(*) FROM song_masters WHERE album_id=albums.id),duration=(SELECT COALESCE(SUM(si.duration),0) FROM song_instances si JOIN song_masters sm ON sm.id=si.master_id WHERE sm.album_id=albums.id),size=(SELECT COALESCE(SUM(si.size),0) FROM song_instances si JOIN song_masters sm ON sm.id=si.master_id WHERE sm.album_id=albums.id),updated_at=unixepoch() WHERE id IN ('pending-uploads','al-7e5eae45c8','al-e9abb8fbe6','al-00d48fe122','al-1c10f4d14a','al-f88b0a5876','al-f249e24866','al-eb1cffa10c','al-4abb0b6368','al-8829e799ff');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'version-group-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT (changes()=10);
