-- Atomic candidate for two verified distinct PCM editions. Do not run against production without a fresh preflight.
WITH c AS (SELECT CASE WHEN instr(se.path,'人声版')>0 THEN 'human' ELSE 'yanhe' END edition,sm.id,se.display_name FROM song_masters sm JOIN song_instances si ON si.master_id=sm.id JOIN storage_entries se ON se.instance_id=si.id AND se.kind='file' JOIN storage_objects so ON so.id=si.storage_object_id WHERE instr(se.path,'你的灵魂长出一支玫瑰')>0 AND (instr(se.path,'人声版')>0 OR instr(se.path,'言和版')>0) AND sm.album_id='pending-uploads' AND sm.track IS NULL AND sm.disc IS NULL AND si.suffix='wav' AND si.missing=0 AND si.tag_scanned=1 AND so.physical_key='objects/'||so.id||'.wav'), g(ok) AS (SELECT COUNT(*)=26 AND COUNT(DISTINCT id)=26 AND SUM(edition='human')=13 AND SUM(edition='yanhe')=13 AND COUNT(DISTINCT edition||':'||CAST(substr(display_name,1,2) AS INTEGER))=26 FROM c)
INSERT INTO album_display_groups(id,display_name,sort_name,created_at,updated_at) SELECT 'ag-rose-2025-vocal-editions','你的灵魂长出一支玫瑰','你的灵魂长出一支玫瑰',unixepoch(),unixepoch() WHERE (SELECT ok FROM g) AND (SELECT song_count FROM albums WHERE id='pending-uploads')=581 AND NOT EXISTS(SELECT 1 FROM album_display_groups WHERE id='ag-rose-2025-vocal-editions');
SELECT CASE WHEN changes()=1 THEN 1 ELSE abs(-9223372036854775808) END;
INSERT INTO albums(id,name,sort_name,song_count,duration,size,compilation,created_at,updated_at) VALUES ('al-rose-2025-human','你的灵魂长出一支玫瑰（人声版）','你的灵魂长出一支玫瑰 人声版',13,3230,569829020,0,unixepoch(),unixepoch()),('al-rose-2025-yanhe','你的灵魂长出一支玫瑰（言和版）','你的灵魂长出一支玫瑰 言和版',13,3260,575363276,0,unixepoch(),unixepoch());
SELECT CASE WHEN changes()=2 THEN 1 ELSE abs(-9223372036854775808) END;
WITH c AS (SELECT CASE WHEN instr(se.path,'人声版')>0 THEN 'human' ELSE 'yanhe' END edition,sm.id,se.display_name FROM song_masters sm JOIN song_instances si ON si.master_id=sm.id JOIN storage_entries se ON se.instance_id=si.id AND se.kind='file' WHERE instr(se.path,'你的灵魂长出一支玫瑰')>0 AND (instr(se.path,'人声版')>0 OR instr(se.path,'言和版')>0) AND sm.album_id='pending-uploads') UPDATE song_masters SET album_id=CASE WHEN (SELECT edition FROM c WHERE c.id=song_masters.id)='human' THEN 'al-rose-2025-human' ELSE 'al-rose-2025-yanhe' END,disc=1,track=(SELECT CAST(substr(display_name,1,2) AS INTEGER) FROM c WHERE c.id=song_masters.id),updated_at=unixepoch() WHERE id IN(SELECT id FROM c);
SELECT CASE WHEN changes()=26 THEN 1 ELSE abs(-9223372036854775808) END;
INSERT INTO album_display_group_members(group_id,album_id,sort_order) VALUES('ag-rose-2025-vocal-editions','al-rose-2025-human',0),('ag-rose-2025-vocal-editions','al-rose-2025-yanhe',1);
SELECT CASE WHEN changes()=2 THEN 1 ELSE abs(-9223372036854775808) END;
UPDATE albums SET song_count=(SELECT COUNT(*) FROM song_masters WHERE album_id=albums.id),duration=(SELECT COALESCE(SUM(duration),0) FROM song_masters WHERE album_id=albums.id),size=(SELECT COALESCE(SUM(si.size),0) FROM song_instances si JOIN song_masters sm ON sm.id=si.master_id WHERE sm.album_id=albums.id),updated_at=unixepoch() WHERE id IN('pending-uploads','al-rose-2025-human','al-rose-2025-yanhe');
SELECT CASE WHEN changes()=3 THEN 1 ELSE abs(-9223372036854775808) END;
SELECT CASE WHEN (SELECT song_count FROM albums WHERE id='al-rose-2025-human')=13 AND (SELECT song_count FROM albums WHERE id='al-rose-2025-yanhe')=13 AND (SELECT COUNT(*) FROM song_masters WHERE album_id IN('al-rose-2025-human','al-rose-2025-yanhe') AND disc=1 AND track BETWEEN 1 AND 13)=26 THEN 1 ELSE abs(-9223372036854775808) END;
