WITH w(master_id,album_id,artist_id,album_artist_id,title,track,disc,duration,has_lyrics,has_rich_lyrics,cover_r2_key,instance_id,source_id,source_type,storage_uri,suffix,size,instance_duration,missing,tag_scanned,storage_object_id,source_etag,entry_id,entry_source_id,parent_id,path,display_name,kind,entry_object_id,companion_of,physical_key,legacy_key,object_size,object_etag,object_suffix,content_type) AS (VALUES
 ('sm-upload-1c5e734b-599','pending-uploads','unknown-artist',NULL,'10  -最后的歌',NULL,NULL,259,0,0,NULL,'si-upload-1fe48367-3ca','r2-local','original','r2://objects/obj_790adcf9317cb20f.wav','wav',45619436,259,0,1,'obj_790adcf9317cb20f','4712159da2cb9e921adf03fe6016734c','se-a15a32d5a9004fb1bef0b8853b1c290d','r2-local','se-a1fc619bab3a4b249497ab6c3a8057f1','平四1-6/平行四界5/10  -最后的歌.wav','10  -最后的歌.wav','file','obj_790adcf9317cb20f',NULL,'objects/obj_790adcf9317cb20f.wav',NULL,45619436,'4712159da2cb9e921adf03fe6016734c','wav','audio/wav')
), guard AS (
 SELECT CASE WHEN (SELECT COUNT(*) FROM w)=1
 AND (SELECT COUNT(*) FROM w c JOIN song_masters sm ON sm.id=c.master_id JOIN song_instances si ON si.id=c.instance_id AND si.master_id=sm.id JOIN storage_entries se ON se.id=c.entry_id AND se.instance_id=si.id JOIN storage_objects so ON so.id=c.entry_object_id WHERE sm.album_id IS c.album_id AND sm.artist_id IS c.artist_id AND sm.album_artist_id IS c.album_artist_id AND sm.title IS c.title AND sm.track IS c.track AND sm.disc IS c.disc AND sm.duration IS c.duration AND sm.lyrics IS NULL AND sm.lyrics_rich IS NULL AND sm.cover_r2_key IS c.cover_r2_key AND si.source_id IS c.source_id AND si.source_type IS c.source_type AND si.storage_uri IS c.storage_uri AND si.suffix IS c.suffix AND si.size IS c.size AND si.duration IS c.instance_duration AND si.missing IS c.missing AND si.tag_scanned IS c.tag_scanned AND si.storage_object_id IS c.storage_object_id AND si.source_etag IS c.source_etag AND se.source_id IS c.entry_source_id AND se.parent_id IS c.parent_id AND se.path IS c.path AND se.display_name IS c.display_name AND se.kind IS c.kind AND se.object_id IS c.entry_object_id AND se.companion_of IS c.companion_of AND so.physical_key IS c.physical_key AND so.legacy_key IS c.legacy_key AND so.size IS c.object_size AND so.etag IS c.object_etag AND so.suffix IS c.object_suffix AND so.content_type IS c.content_type)=1
 AND (SELECT COUNT(*) FROM albums WHERE id='pending-uploads' AND song_count=523 AND duration=116804 AND size=20308060661)=1
 AND (SELECT COUNT(*) FROM albums WHERE id='al-ac89e8964d' AND name='平行四界Quadimension 5' AND sort_name='平行四界quadimension 5' AND year=2016 AND genre IS NULL AND cover_r2_key='covers/al-ac89e8964d' AND song_count=10 AND duration=2691 AND size=457556360 AND compilation=0)=1
 AND (SELECT COUNT(*) FROM song_masters sm JOIN song_instances si ON si.master_id=sm.id JOIN storage_entries se ON se.instance_id=si.id JOIN storage_objects so ON so.id=si.storage_object_id WHERE sm.id='486' AND sm.album_id='al-ac89e8964d' AND sm.artist_id='ar-2b4aeae2d9' AND sm.album_artist_id='ar-b86d3071fc' AND sm.title='最后的歌' AND sm.track=10 AND sm.disc=1 AND sm.duration=259 AND sm.lyrics IS NULL AND sm.lyrics_rich IS NULL AND sm.cover_r2_key IS NULL AND si.id='si-mirror-ed8ee36e679948c4' AND si.source_id='r2-local' AND si.source_type='original' AND si.storage_uri='r2://objects/obj_10700e8c4872ea79.flac' AND si.suffix='flac' AND si.size=23568474 AND si.duration=259 AND si.missing=0 AND si.tag_scanned=1 AND si.storage_object_id='obj_10700e8c4872ea79' AND si.source_etag='7ee74890fe63fbf3ca83539aa70bc9b6' AND se.id='se-7f3f6ce64a5e4a94ad5db0ff76e74bad' AND se.source_id='r2-local' AND se.parent_id='se-af38e2f70e2f4bc08b642e8d310370dc' AND se.path='平行四界Quadimension 5/10 - 最后的歌.flac' AND se.display_name='10 - 最后的歌.flac' AND se.kind='file' AND se.object_id='obj_10700e8c4872ea79' AND se.companion_of IS NULL AND so.physical_key='objects/obj_10700e8c4872ea79.flac' AND so.legacy_key IS NULL AND so.suffix='flac' AND so.content_type IS NULL AND so.size=23568474 AND so.etag='7ee74890fe63fbf3ca83539aa70bc9b6')=1
 AND NOT EXISTS(SELECT 1 FROM albums WHERE id='al-q5-wav-alternate' OR name='平行四界Quadimension 5 (WAV Alternate)')
 AND NOT EXISTS(SELECT 1 FROM album_display_groups WHERE id='ag-q5-edition-variants' OR display_name='平行四界Quadimension 5')
 AND NOT EXISTS(SELECT 1 FROM album_display_group_members WHERE album_id='al-ac89e8964d')
 THEN 1 ELSE 0 END ok
)
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() FROM guard WHERE ok=0;
INSERT INTO albums(id,name,sort_name,year,genre,cover_r2_key,song_count,duration,size,compilation,created_at,updated_at) VALUES('al-q5-wav-alternate','平行四界Quadimension 5 (WAV Alternate)','平行四界quadimension 5 wav alternate',2016,NULL,'covers/al-ac89e8964d',0,0,0,0,unixepoch(),unixepoch());
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() WHERE changes()!=1;
UPDATE song_masters SET album_id='al-q5-wav-alternate',artist_id='ar-2b4aeae2d9',album_artist_id='ar-b86d3071fc',title='最后的歌',track=10,disc=1,updated_at=unixepoch() WHERE id='sm-upload-1c5e734b-599' AND album_id='pending-uploads' AND track IS NULL AND disc IS NULL;
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() WHERE changes()!=1;
UPDATE albums SET song_count=(SELECT COUNT(*) FROM song_masters WHERE album_id=albums.id),duration=(SELECT COALESCE(SUM(duration),0) FROM song_masters WHERE album_id=albums.id),size=(SELECT COALESCE(SUM(si.size),0) FROM song_masters sm JOIN song_instances si ON si.master_id=sm.id WHERE sm.album_id=albums.id),updated_at=unixepoch() WHERE id IN('pending-uploads','al-q5-wav-alternate');
INSERT INTO album_display_groups(id,display_name,sort_name) SELECT 'ag-q5-edition-variants','平行四界Quadimension 5','平行四界Quadimension 5' WHERE EXISTS(SELECT 1 FROM albums WHERE id='al-ac89e8964d' AND name='平行四界Quadimension 5' AND song_count=10) AND EXISTS(SELECT 1 FROM albums WHERE id='al-q5-wav-alternate' AND name='平行四界Quadimension 5 (WAV Alternate)' AND song_count=1) AND NOT EXISTS(SELECT 1 FROM album_display_groups WHERE id='ag-q5-edition-variants' OR display_name='平行四界Quadimension 5');
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() WHERE changes()!=1;
INSERT INTO album_display_group_members(group_id,album_id,sort_order) VALUES('ag-q5-edition-variants','al-ac89e8964d',0),('ag-q5-edition-variants','al-q5-wav-alternate',1);
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() WHERE changes()!=2;
INSERT INTO work_queue(id,task_type,payload,status,created_at) SELECT 'q5-wav-guard-failed','metadata','{}','guard_failed',unixepoch() WHERE (SELECT COUNT(*) FROM song_masters WHERE id='sm-upload-1c5e734b-599' AND album_id='al-q5-wav-alternate' AND artist_id='ar-2b4aeae2d9' AND album_artist_id='ar-b86d3071fc' AND title='最后的歌' AND track=10 AND disc=1 AND duration=259)!=1 OR (SELECT COUNT(*) FROM album_display_group_members WHERE group_id='ag-q5-edition-variants')!=2 OR (SELECT song_count FROM albums WHERE id='pending-uploads')!=522 OR (SELECT duration FROM albums WHERE id='pending-uploads')!=116545 OR (SELECT size FROM albums WHERE id='pending-uploads')!=20262441225;
