WITH c(master_id,instance_id,entry_id,object_id,title_snapshot,disc_snapshot,track_snapshot) AS (VALUES
('sm-upload-d3e438fe-c79','si-upload-9b3a8f8b-6d7','se-d5ca35ed0e5a40409760dc42d74c7172','obj_9551e3421ee8e30e','01 衔风与愿',NULL,NULL)
)
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'pending-backfill-guard','metadata','{}','guard_failed',unixepoch() WHERE NOT ((SELECT COUNT(*) FROM c JOIN song_masters sm ON sm.id=c.master_id AND sm.album_id='pending-uploads' AND sm.title IS c.title_snapshot AND sm.disc IS c.disc_snapshot AND sm.track IS c.track_snapshot JOIN song_instances si ON si.id=c.instance_id AND si.master_id=sm.id AND si.source_id='r2-local' AND si.source_type='original' AND si.missing=0 AND si.tag_scanned=1 AND lower(si.suffix)='wav' AND si.storage_object_id=c.object_id JOIN storage_entries se ON se.id=c.entry_id AND se.instance_id=si.id AND se.kind='file' AND se.source_id='r2-local' AND se.parent_id='se-c7876d840373456ca0d7f774c5f39224' AND se.object_id=si.storage_object_id JOIN storage_objects so ON so.id=c.object_id WHERE (SELECT COUNT(*) FROM storage_entries f WHERE f.instance_id=si.id AND f.kind='file')=1)=1 AND NOT EXISTS (SELECT 1 FROM albums WHERE id='al-d1eb61467eb114e11bfea9d9690057c2') AND NOT EXISTS (SELECT 1 FROM song_masters WHERE id IN ('sm-upload-d3e438fe-c79') GROUP BY lower(trim(title)) HAVING COUNT(*)>1) AND NOT EXISTS (SELECT 1 FROM song_masters WHERE id IN ('sm-upload-d3e438fe-c79') AND track IS NOT NULL GROUP BY COALESCE(disc,0),track HAVING COUNT(*)>1) AND (SELECT COUNT(*) FROM storage_entries se JOIN song_instances si ON si.id=se.instance_id AND si.source_id='r2-local' AND lower(si.suffix)='wav' JOIN song_masters sm ON sm.id=si.master_id WHERE se.kind='file' AND se.source_id='r2-local' AND se.parent_id='se-c7876d840373456ca0d7f774c5f39224' AND sm.album_id!='pending-uploads')=0 AND (SELECT COUNT(*) FROM storage_entries se JOIN song_instances si ON si.id=se.instance_id AND si.source_id='r2-local' AND lower(si.suffix)='wav' JOIN song_masters sm ON sm.id=si.master_id WHERE se.kind='file' AND se.source_id='r2-local' AND se.parent_id='se-c7876d840373456ca0d7f774c5f39224' AND sm.album_id!='pending-uploads' AND sm.id NOT IN (''))=0 AND (SELECT COUNT(*) FROM song_masters sm JOIN song_instances si ON si.master_id=sm.id JOIN storage_entries se ON se.instance_id=si.id AND se.kind='file' WHERE sm.id IN ('') AND sm.album_id IN ('') AND se.source_id='r2-local' AND se.parent_id='se-c7876d840373456ca0d7f774c5f39224' AND lower(si.suffix)='wav')=0);
INSERT INTO albums (id,name,sort_name,created_at,updated_at) SELECT 'al-d1eb61467eb114e11bfea9d9690057c2','衔风与愿','衔风与愿',unixepoch(),unixepoch() WHERE NOT EXISTS (SELECT 1 FROM albums WHERE id='al-d1eb61467eb114e11bfea9d9690057c2');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'pending-backfill-guard','metadata','{}','guard_failed',unixepoch() WHERE changes()!=1;
UPDATE song_masters AS sm SET album_id='al-d1eb61467eb114e11bfea9d9690057c2',updated_at=unixepoch() WHERE sm.id='sm-upload-d3e438fe-c79' AND sm.album_id='pending-uploads' AND EXISTS (SELECT 1 FROM song_instances si JOIN storage_entries se ON se.instance_id=si.id AND se.kind='file' JOIN storage_objects so ON so.id=si.storage_object_id WHERE si.id='si-upload-9b3a8f8b-6d7' AND si.master_id=sm.id AND sm.title IS '01 衔风与愿' AND sm.disc IS NULL AND sm.track IS NULL AND si.source_id='r2-local' AND si.source_type='original' AND si.missing=0 AND si.tag_scanned=1 AND lower(si.suffix)='wav' AND si.storage_object_id='obj_9551e3421ee8e30e' AND so.id='obj_9551e3421ee8e30e' AND se.id='se-d5ca35ed0e5a40409760dc42d74c7172' AND se.source_id='r2-local' AND se.parent_id='se-c7876d840373456ca0d7f774c5f39224' AND se.object_id=si.storage_object_id AND se.path='衔风与愿/01 衔风与愿.wav' AND se.display_name='01 衔风与愿.wav' AND (SELECT COUNT(*) FROM storage_entries f WHERE f.instance_id=si.id AND f.kind='file')=1);
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'pending-backfill-guard','metadata','{}','guard_failed',unixepoch() WHERE changes()!=1;
UPDATE albums SET song_count=(SELECT COUNT(*) FROM song_masters WHERE song_masters.album_id=albums.id),size=(SELECT COALESCE(SUM(si.size),0) FROM song_instances si JOIN song_masters sm ON sm.id=si.master_id WHERE sm.album_id=albums.id),updated_at=unixepoch() WHERE id IN ('pending-uploads','al-d1eb61467eb114e11bfea9d9690057c2');
INSERT INTO work_queue (id,task_type,payload,status,created_at) SELECT 'pending-backfill-guard','metadata','{}','guard_failed',unixepoch() WHERE changes()!=2 OR (SELECT COUNT(*) FROM song_masters WHERE album_id='al-d1eb61467eb114e11bfea9d9690057c2')!=1 OR (SELECT song_count FROM albums WHERE id='al-d1eb61467eb114e11bfea9d9690057c2')!=1 OR (SELECT size FROM albums WHERE id='al-d1eb61467eb114e11bfea9d9690057c2')!=(SELECT COALESCE(SUM(si.size),0) FROM song_instances si JOIN song_masters sm ON sm.id=si.master_id WHERE sm.album_id='al-d1eb61467eb114e11bfea9d9690057c2');
